Globs:
  - "**/*.cr"
  - "!samples"
  - "!lib"

Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
    - src/ext/http/cookie.cr
  Enabled: true
  Severity: Convention
